site_uses_local_db: "{{ site_env.db_host == 'localhost' }}"
nginx_rails_app_conf: rails_app.conf.j2
nginx_ssl_path: "{{ nginx_path }}/ssl"

ssl_default_site:
  no_default:
    site_hosts:
      - canonical: example.com
    ssl:
      enabled: true
      provider: self-signed
    multisite: {}

nginx_sites_confs:
  - src: no-default.conf.j2
  - src: ssl.no-default.conf.j2
    enabled: "{{ sites_use_ssl }}"

# HSTS defaults
nginx_hsts_max_age: 31536000
nginx_hsts_include_subdomains: true
nginx_hsts_preload: false

# HSTS helpers
hsts_max_age: "{{ item.value.ssl.hsts_max_age | default(nginx_hsts_max_age) }}"
hsts_include_subdomains: "{{ item.value.ssl.hsts_include_subdomains | default(nginx_hsts_include_subdomains) | ternary('includeSubDomains', None) }}"
hsts_preload: "{{ item.value.ssl.hsts_preload | default(nginx_hsts_preload) | ternary('preload', None) }}"

# Fastcgi cache params
nginx_cache_duration: 30s
nginx_skip_cache_uri: ""
nginx_skip_cache_cookie: ""
nginx_cache_background_update: "on"

# Nginx includes
nginx_includes_templates_path: nginx-includes
nginx_includes_deprecated: roles/wordpress-setup/templates/includes.d
nginx_includes_pattern: "^({{ nginx_includes_templates_path | regex_escape }}|{{ nginx_includes_deprecated | regex_escape }})/(.*)\\.j2$"
nginx_includes_d_cleanup: true

# h5bp helpers
not_dev: "{{ env != 'development' }}"
h5bp: "{{ item.value.h5bp | default({}) }}"
h5bp_cache_file_descriptors_enabled: "{{ h5bp.cache_file_descriptors | default(not_dev) }}"
h5bp_extra_security_enabled: "{{ h5bp.extra_security | default(true) }}"
h5bp_no_transform_enabled: "{{ h5bp.no_transform | default(false) }}"
h5bp_x_ua_compatible_enabled: "{{ h5bp.x_ua_compatible | default(true) }}"
h5bp_cache_busting_enabled: "{{ h5bp.cache_busting | default(false) }}"
h5bp_cross_domain_fonts_enabled: "{{ h5bp.cross_domain_fonts | default(true) }}"
h5bp_expires_enabled: "{{ h5bp.expires | default(false) }}"
h5bp_protect_system_files_enabled: "{{ h5bp.protect_system_files | default(true) }}"
