---
- name: Add Phusion Passenger APT Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
  become: yes

- name: Add Phusion Passenger APT Repository
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main
    state: present
    update-cache: yes
  become: yes

- name: Install
  apt: name={{ item }} state=present
  become: yes
  with_items: "{{ passenger_apt_packages[ansible_distribution_release] }}"
  update-cache: yes
  cache-valid-time: 0


- name: Enable Passenger Module
  file:
    src: /usr/share/nginx/modules-available/mod-http-passenger.load
    dest: /etc/nginx/modules-enabled/50-mod-http-passenger.conf
    state: link
  become: yes
  when: ansible_distribution_release == "bionic"