- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.6

- name: bbatsche-postgresql
  src: bbatsche.PostgreSQL
  version: v4.1.0

- name: geerlingguy-nodejs
  src: geerlingguy.nodejs
  version: 4.2.0