apt_cache_valid_time: 3600
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
ntp_timezone: Etc/UTC
ntp_manage_config: true
www_root: /srv/www
ip_whitelist:
  - "{{ (env == 'development') | ternary(ansible_default_ipv4.gateway, ipify_public_ip | default('')) }}"

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_rails_apps.*.*_salt    -- matches vault_rails_apps.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_db_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_rails_apps

nginx_ppa: deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ ansible_distribution_release }} main
passenger_app: yes

apt_packages_custom:
  build-essential: "{{ apt_package_state }}"
  patch: "{{ apt_package_state }}"
  ruby-dev: "{{ apt_package_state }}"
  zlib1g-dev: "{{ apt_package_state }}"
  liblzma-dev: "{{ apt_package_state }}"

nodejs_install_npm_user: "{{ web_group }}"
nodejs_version: "10.x"
copy_nginx_ruby_conf: no