# Define accompanying passwords/secrets in group_vars/production/vault.yml

rails_apps:
  krmb:
    site_hosts:
      - canonical: example.com
        redirects:
          - www.example.com
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
