---
- name: disable temporary challenge sites
  import_tasks: disable_challenge_sites.yml

- name: restart memcached
  service:
    name: memcached
    state: restarted

- import_tasks: reload_nginx.yml
